version: "3"
services:
  api:
    build:
      context: ./api
    volumes:
      - ./api:/var/www/html
    ports:
      - "8000:80"
    networks:
      - app-network

  frontend:
    build:
      context: ./greatstudy
    volumes:
      - ./greatstudy:/app
      - /app/node_modules
    ports:
      - "8080:8080"
    networks:
      - app-network

networks:
  app-network:
