version: "3"
services:
  backend:
    build:
      context: ./api
    volumes:
      - ./api:/var/www/html
    ports:
      - "8000:80"
    networks:
      - app-network

  frontend:
    build:
      context: ./greatstudy
    volumes:
      - ./greatstudy:/app
      - /app/node_modules
    ports:
      - "8080:8080"
    networks:
      - app-network

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "1025:1025"  # SMTP ポート
      - "8025:8025"  # Web UI ポート

networks:
  app-network:
